version: '3'
services:
  hub:
    image: selenium/hub:3.14.0-gallium
    container_name: selenium-hub
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    container_name: firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  nginx:
    image: nginx:stable
    container_name: nginx-docs
    ports:
      - "8888:80"
    volumes:
      - /tmp/build/html:/usr/share/nginx/html:ro
