asciidoc:
  index:
    file: index.adoc
  multipage_level: 2

build:
  dir: /tmp/build
  html:
    dir: /tmp/build/html

checkers:
  pattern:
    blacklist: blacklist.txt

search:
  index:
    file: lunrindex.json
  db:
    file: lunrdb.json
  exclude:
    - docinfo*.html
    - index.html
    - Imprint.html
    - ContactUs.html

log:
  file: /tmp/log.json

notify:
  slack:
      file: /tmp/slack.json

toc:
  json_file: toc.json
  html_file: toc.html
