[#CreditCard_PSD2]
== What is PSD 2?

====
.The Second Payment Service Directive (PSD2) in a Nutshell

- *New Regulation:* EU's Second Payment Service Directive (PSD2) for
online payments within the European Economic Area (EEA)
- *Requires:* Strong Customer Authentication (SCA)
- *What it is:* A measure to combat fraud in card-not-present
transactions
- *Who is affected:* Issuers, acquirers, and merchants in the EEA

//-
====

The EU's Second **P**ayment **S**ervice **D**irective (PSD2) aims to reduce
fraud in the European e-commerce sector. Since the largest percentage of
all card fraud in Europe happens in card-not-present transactions, the
PSD2 makes **S**trong **C**ustomer **A**uthentication (SCA) mandatory
for *consumer-initiated online payments* within the **E**uropean
**E**conomic **A**rea (EEA).

While the regulations defined in _PSD2_ apply to acquirers and issuers,
the effects will also concern EEA merchants and consumers.

To get you ready for SCA, the https://www.emvco.com/about/overview/[EMVCo] have developed
<<CreditCard_3DS2, 3D Secure 2>>, a new authentication protocol for payment card transactions.

[#CreditCard_PSD2_SCA]
=== What is Strong Customer Authentication (SCA)?

_Strong Customer Authentication_ is a security measure that relies on
two-factor authentication to verify the identity of the consumer in a
payment transaction. As a result, these factors are strictly
consumer-based. _SCA_ can combine two of the following three factors,
which must be strictly independent of each other:

- *Knowledge* +
This factor relies on the consumer's unique knowledge of a password or a
PIN. Knowledge must not be easily accessible by unauthorized parties.
The https://eba.europa.eu/about-us[European Banking Authority (EBA)] has determined that credit card number, CVV and
expiry date are not valid knowledge, as these are printed on the credit
card.
- *Possession* +
This factor relies on the consumer's possession to verify a payment.
For example, hardware, such as smartphones and tablets registered to the
consumer, can be used as a second verification instance.
- *Inherence* +
This factor uses biometrics to verify the consumer's identity, for
example, a fingerprint or a facial scan.

//-

For all payments authenticated with Strong Customer Authentication, as
well as those exempted from SCA, the payment service provider must
ensure that the fraud rates for online payments are the same as, or
lower than the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> set out in the PSD2.

[#CreditCard_PSD2_SCA_Exemptions]
=== Exemptions to Strong Customer Authentication

Certain types of transactions may be exempted from Strong Customer
Authentication. It is up to your bank/acquirer to request these
exemptions for you.

[#CreditCard_PSD2_SCA_Exemptions_LowValue]
==== Low Value Transactions

- SCA does NOT apply to transactions below 30 EUR.
- SCA does NOT apply when the cumulative amount of previous transactions
since the last Strong Customer Authentication does not exceed 100 EUR.
- SCA does NOT apply when five or less consecutive individual online
transactions have been made (remember that in this case, none of those
two-to-five payments have been over 30 EUR, and their total does not
exceed 100 EUR).
- The fraud rates for low value transactions must be the same as, or
below the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

[#CreditCard_PSD2_SCA_Exemptions_Recurring]
==== Recurring Transactions

- SCA needs to apply when the consumer initiates the first in a series
of recurring transactions with the same amount and the same merchant.
- SCA does NOT apply to all subsequent recurring transactions.
- The fraud rates for recurring transactions must be the same as, or
below the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

[#CreditCard_PSD2_SCA_Exemptions_LowRisk]
==== Low-risk transactions

- SCA does NOT apply to low-risk transactions.
- To determine whether an online transaction is low-risk, acquirers and
issuers may perform real-time risk analysis, to identify, for example,
abnormal spending patterns, known fraud scenarios, and abnormal location
of the consumer.
- Low risk transactions can only be exempted if the fraud rates for
these transactions are the same as, or below the
<<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

[#CreditCard_PSD2_SCA_Exemptions_WhiteList]
==== White-Listing

- SCA does NOT apply to online payments from a consumer to a
white-listed merchant.
- Consumers can white-list 'trusted beneficiaries' - merchants of their
choice to be included on a list maintained by the consumer's bank. SCA
is only required for the first online transaction.
- White-listed transactions can only be exempted if the fraud rates for
these transactions are the same as, or below the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

[#CreditCard_PSD2_SCA_Exemptions_Corporate]
==== Secure Corporate Transactions

- SCA does NOT apply to secure B2B payments via dedicated payment
processes and protocols which are not available to consumers.
- Secure corporate transactions can only be exempted if the fraud rates
for these transactions are the same as, or below the
<<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

[#CreditCard_PSD2_Fraud]
==== Calculation of Fraud Rates

.EU reference fraud rate for remote electronic card-based payments
[%autowidth]
|===
|Exemption Threshold Value (ETV) |Fraud Rate

| EUR 500 | 0.01 %
| EUR 250 | 0.06 %
| EUR 100 | 0.13 %
|===

//-
