:date-pattern: YYYY-MM-DD
:timestamp-pattern: YYYY-MM-DDThh:mm:ssZ

[#CC_Fields]
== Fields

This is the general field reference for _credit card_ transactions.

====
- Format: XML 
- POST requests and responses

//-
====

We provide the request and the response fields in two separate sections:

- <<CC_Fields_xmlelements_request, _Request_>> contains those fields sent in the request (and usually in the response).
- <<CC_Fields_xmlelements_response, _Response_>> contains those fields sent in the response only.

//-

The fields are ordered hierarchically and in separate tables. ``payment`` is the top parent element and all fields that are part of ``payment`` are listed <<CC_Fields_xmlelements_request_payment, in the ``payment`` table>>. 

Some fields listed in this table are _complex type_ fields, e.g. ``payment.account-holder``. _Complex type_ fields are parents to further fields. We offer separate field tables for all parent elements and their respective fields.

NOTE: The tables are sorted alphabetically. Use *Ctrl + F* if you are looking for a specific field.

For example, ``payment.account-holder`` is a parent of ``address``. Click on the link in the table to view the fields contained in a _complex type_ field.


[#CC_Fields_intro_elements]
=== Field Definitions

Each field table contains the following columns:

- <<APIRef_FieldDefs_Name, Name>>
- <<APIRef_FieldDefs_Cardinality, Cardinality>> (for request elements only)
- <<APIRef_FieldDefs_DataTypes, Data Type>>
- <<APIRef_FieldDefs_Size, Size>> (for request elements only)

//-

IMPORTANT: Field definitions may vary by transaction type. Deviations from standard field definitions are given with the respective transaction type.


[#CC_Fields_xmlelements]
=== XML Elements
Click the X in the respective column for request and response fields.

Please refer to our <<Appendix_Xml, XSD>> for the structural relationship between these fields.


[cols="m,,"]
|===
| Field | Request | Response

| payment
| <<CC_Fields_xmlelements_request_payment, X>>
| <<CC_Fields_xmlelements_response_payment, X>>

| account-holder
| <<CC_Fields_xmlelements_request_accountholder, X>>
| 

| account-info
| <<CC_Fields_xmlelements_request_accountinfo, X>>
| 

| address
| <<CC_Fields_xmlelements_request_address, X>>
| 

| airline-industry
| <<CC_Fields_xmlelements_request_airlineindustry, X>>
| 

| audit
| <<CC_Fields_xmlelements_request_audit, X>>
| 

| avs
| 
| <<CC_Fields_xmlelements_response_avs, X>>

| browser
| <<CC_Fields_xmlelements_request_browser, X>>
| 

| card
| <<CC_Fields_xmlelements_request_card, X>>
|  

| card-emv
| <<CC_Fields_xmlelements_request_cardEMV, X>>
| <<CC_Fields_xmlelements_response_cardEMV, X>>

// | card-pin
// | <<CC_Fields_xmlelements_cardPIN, X>>
// | 

// |card-raw
// | <<CC_Fields_xmlelements_cardRaw, X>>
// | 

| card-token
| <<CC_Fields_xmlelements_request_cardtoken, X>>
| 

| credit-sender-data
| <<CC_Fields_xmlelements_request_creditsenderdata, X>>
| 

| cruise-industry
| <<CC_Fields_xmlelements_request_cruiseindustry, X>>
| 

| custom-fields
| <<CC_Fields_xmlelements_request_customfield, X>>
| <<CC_Fields_xmlelements_response_customfield, X>>

| device
| <<CC_Fields_xmlelements_request_device, X>>
| 

// | encryption-context
// | <<CC_Fields_xmlelements_request_encryptionContext, X>>
// | 

| iso
| <<CC_Fields_xmlelements_request_ISO, X>>
| 

| notifications
| <<CC_Fields_xmlelements_request_notification, X>>
| 

| order-items
| <<CC_Fields_xmlelements_request_orderitem, X>>
| 

| payment-methods
| <<CC_Fields_xmlelements_request_paymentmethod, X>>
|

| risk-info
| <<CC_Fields_xmlelements_request_riskinfo, X>>
| 

| segment
| <<CC_Fields_xmlelements_request_segment, X>>
| 

| shipping
| <<CC_Fields_xmlelements_request_shipping, X>>
| 

| status
| 
| <<CC_Fields_xmlelements_response_status, X>>

| sub-merchant-info
| <<CC_Fields_xmlelements_request_submerchantinfo, X>>
| 

| three-d
| <<CC_Fields_xmlelements_request_threed, X>>
| <<CC_Fields_xmlelements_response_threed, X>>
|===

[#CC_Fields_xmlelements_request]
=== Request

[#CC_Fields_xmlelements_request_payment]
.``payment``

Additional ``payment`` fields can be found in the
<<CC_Fields_xmlelements_response_payment, Response > ``payment``>> section.

[%autowidth]
[cols="m,,,,a"]
|===
| Field | <<APIRef_FieldDefs_Cardinality, M/O>> | Datatype | Size | Description

include::{root}/include/fields/rest_cc/request/req-payment.adoc[]
|===

[#CC_Fields_xmlelements_request_accountholder]
.account-holder

``account-holder`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. +
With the ``account-holder`` merchants can gather detailed information about the
consumer. Please provide all the ``account-holder`` data in your request to make fraud prevention easier.

[%autowidth]
[cols="m,,,,a"]
|===
| Field | <<APIRef_FieldDefs_Cardinality, M/O>> | Datatype | Size | Description

include::{root}/include/fields/rest_cc/request/req-account-holder.adoc[]
include::{root}/include/fields/rest_cc/request/req-account-holder-parents.adoc[]

|===


[#CC_Fields_xmlelements_request_accountinfo]
.account-info

``account-info`` is a child of
<<CC_Fields_xmlelements_request_accountholder, account-holder>>. +
``account-info`` fields are used with 3D Secure 2. With ``account-info`` merchants can gather detailed information about the consumer. Please provide all the ``account-info`` data in your 3D Secure 2 request to make fraud prevention easier.

include::{root}/include/fields/rest_cc/request/req-account-info.adoc[]

[#CC_Fields_xmlelements_request_address]
.address



``address`` is a child of
<<CC_Fields_xmlelements_request_accountholder, account-holder>>, <<CC_Fields_xmlelements_request_shipping, shipping>>, and <<CC_Fields_xmlelements_request_airlineindustry, airline-industry>>. It is used to specify the consumer's address and can refer to


- the consumer (for ``account-holder``). The account holder's address is used as the billing address.
- the consumer's shipping address (for ``shipping``). For 3D Secure 2 transactions it is highly recommended to send ``shipping.address`` data in any case, as a complete set of ``shipping.address`` data reduces the likelihood of a challenge test.
- the ticket issuer (for ``airline-industry``).


Data can be provided optionally but it helps with fraud checks, if ``address`` is complete.

include::{root}/include/fields/rest_cc/request/req-address.adoc[]


[#CC_Fields_xmlelements_request_airlineindustry]
.airline-industry

``airline-industry`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::{root}/include/fields/rest_cc/request/req-airline-industry.adoc[]

[#CC_Fields_xmlelements_request_audit]
.audit

``audit`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. 
Audit data is displayed in _{enterprise-portal-abbr}_ for each transaction it has been send with.

include::{root}/include/fields/rest_cc/request/req-audit.adoc[]


[#CC_Fields_xmlelements_request_browser]
.browser

``browser`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::{root}/include/fields/rest_cc/request/req-browser.adoc[]

[#CC_Fields_xmlelements_request_card]
.card

:listname: CC

``card`` is a child of  <<CC_Fields_xmlelements_request_payment, payment>>. ``card`` details are sent only in the first transaction request when the card is used for the first time. Due to
<<CreditCard_PaymentFeatures_Tokenization_Introduction, PCI DSS>> compliance, ``card`` details are immediately replaced by a token. Beginning with the first response, this
token is used for every consecutive transaction (request and response) that is performed
with this credit card. Token data is provided with the
<<CC_Fields_xmlelements_request_cardtoken, card-token>> element.

NOTE: Only the transaction type _detokenize_ returns ``expiration-month``,
``expiration-year`` and ``card-type`` in a response. All the other transaction
types return elements of ``card-token`` in the response.

include::{root}/include/fields/api/request/req-card.adoc[]

:!listname:

[#CC_Fields_xmlelements_request_cardEMV]
.card.card-emv

:listname: CC

include::{root}/include/fields/rest_cc/request/req-card-emv.adoc[tags="**;!response;!responseHeader"]

:!listname:

// [#CC_Fields_xmlelements_cardPIN]
// .card.card-pin

// include::{root}/include/fields/rest_cc/request/req-card-pin.adoc[]


// [#CC_Fields_xmlelements_cardRaw]
// .card.card-raw

// include::{root}/include/fields/rest_cc/request/req-card-raw.adoc[]


[#CC_Fields_xmlelements_request_cardtoken]
.card-token

``card-token`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>> and is the substitute
for <<CC_Fields_xmlelements_request_card, card>>. Due to
<<CreditCard_PaymentFeatures_Tokenization_Introduction, PCI DSS>>
compliance, ``card`` data must not be sent in payment transactions. The _{payment-gateway}_ replaces ``card`` immediately with a token in the transaction response for the first use of a credit card.

include::{root}/include/fields/rest_cc/request/req-card-token.adoc[]


[#CC_Fields_xmlelements_request_creditsenderdata]
.credit-sender-data

``credit-sender-data`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

``credit-sender-data`` is used in OCT non gambling payment processes only.

With this element the merchant can send money to the consumer.
This can be the case, if the merchant is

- an insurance company and has to pay out money to the consumer (insurance case).
- the government and has to pay back taxes.

//-

include::{root}/include/fields/rest_cc/request/req-credit-sender-data.adoc[]

[#CC_Fields_xmlelements_request_cruiseindustry]
.cruise-industry

``cruise-industry`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::{root}/include/fields/rest_cc/request/req-cruise-industry.adoc[]



[#CC_Fields_xmlelements_request_customfield]
.custom-field

``custom-field`` is a child of  
<<CC_Fields_xmlelements_request_payment, payment.custom-fields>>.

In the <<CC_Fields_xmlelements_response_customfield, response > custom-field>> section you can find examples for ready-to-use ``custom-field``.

include::{root}/include/fields/rest_cc/request/req-custom-field.adoc[]


[#CC_Fields_xmlelements_request_device]
.device

``device`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::{root}/include/fields/rest_cc/request/req-device.adoc[]


// [#CC_Fields_xmlelements_request_encryptionContext]
// .encryption-context

// include::{root}/include/fields/rest_cc/request/req-encryption-context.adoc[]


[#CC_Fields_xmlelements_request_ISO]
.iso

include::{root}/include/fields/rest_cc/request/req-iso.adoc[]


[#CC_Fields_xmlelements_request_notification]
.notification

``notification`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment.notifications>>.

``notification`` is used to set up <<GeneralPlatformFeatures_IPN, Instant Payment Notification (IPN)>>. It is highly recommended to use IPN. IPN informs you about the outcome of the individual payment processes. By including ``notification`` in the request
you can overwrite the <<GeneralPlatformFeatures_IPN_Configuration, merchant account configuration>>.

include::{root}/include/fields/rest_cc/request/req-notification.adoc[]

[#CC_Fields_xmlelements_request_orderitem]
.order-item

``order-item`` is a child of
<<CC_Fields_xmlelements_request_payment, payment.order-items>>. This is a field
for order's items filled by the merchant. Order item amount always includes tax.
Tax can be specified either by tax amount or by tax rate.

include::{root}/include/fields/rest_cc/request/req-order-item.adoc[]


//[#CC_Fields_xmlelements_request_payloadfield]
//.payload-field
//
//``payload-field`` is a child of
//<<CC_Fields_xmlelements_request_paymentmethod, payment-methods.payload>>.


[#CC_Fields_xmlelements_request_paymentmethod]
.payment-method

``payment-method`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment.payment-methods>>.

The element ``payment-method`` specifies the payment method used for a transaction.

include::{root}/include/fields/rest_cc/request/req-payment-method.adoc[]


[#CC_Fields_xmlelements_request_periodic]
.periodic

``periodic`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. +
``periodic`` is used, if the payment requires subsequent payments refering to each other such as payments of a subscription or an installment. 

The fields can be ignored if no recurring payment is inteded. For all recurring payments the ``periodic`` fields ``periodic-type`` and ``sequence-type`` are mandatory.

include::{root}/include/fields/rest_cc/request/req-periodic.adoc[]


[#CC_Fields_xmlelements_request_riskinfo]
.risk-info

``risk-info`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment>>.

// Please provide a short explanation for ``risk-info``: Explicit fields for 3D Secure 2? 

include::{root}/include/fields/rest_cc/request/req-risk-info.adoc[]



[#CC_Fields_xmlelements_request_segment]
.segment

``segment`` is a child of
<<CC_Fields_xmlelements_request_airlineindustry, airline-industry.itinerary>> and <<CC_Fields_xmlelements_request_cruiseindustry, cruise-industry.itinerary>>. Itinerary segment data is used e.g. within airline industry and cruise industry to specify itineraries of the flight.

include::{root}/include/fields/rest_cc/request/req-segment.adoc[]



[#CC_Fields_xmlelements_request_shipping]
.shipping

``shipping`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.
For 3D Secure 2 transactions it is highly recommended to send ``shipping`` data in any case, as a complete set of ``shipping`` data reduces the likelihood of a challenge.

[%autowidth]
[cols="m,,,,a"]

|===
include::{root}/include/fields/rest_cc/request/req-shipping.adoc[]

4+| address | <<CC_Fields_xmlelements_request_address, address>> is a child element of ``shipping``.
|===



[#CC_Fields_xmlelements_request_submerchantinfo]
.sub-merchant-info

``sub-merchant-info`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. ``sub-merchant-info`` fields are required for the <<CreditCard_PaymentFeatures_PaymentFacilitator, Payment Facilitator>>. If you want to use ``sub-merchant-info``, all the fields in this table are mandatory for every initial step of a transaction. It is recommended to include ``sub-merchant-info`` in all transaction steps. Otherwise, some transactions cannot be completed successfully. ``state`` is an exception. See ``state`` description for details.

include::{root}/include/fields/rest_cc/request/req-sub-merchant-info.adoc[]


[#CC_Fields_xmlelements_request_threed]
.three-d

``three-d`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

Additional fields can be found in the
<<CC_Fields_xmlelements_response_threed, response > three-d>> section.

[#CreditCard_Fields_ThreeD]
[%autowidth]
[cols="m,,,,a"]
|===
| Fieldname | <<APIRef_FieldDefs_Cardinality, M/O>> | Datatype | Size | Description

include::{root}/include/fields/rest_cc/request/req-three-d.adoc[]

|===

[#CC_Fields_xmlelements_response]
=== Response

[#CC_Fields_xmlelements_response_payment]
.payment

Here you can find the ``payment`` element fields which are sent in the response only.

include::{root}/include/fields/rest_cc/response/res-payment.adoc[]


[#CC_Fields_xmlelements_response_avs]
.avs

``avs`` is a child of
<<CC_Fields_xmlelements_response_payment, payment>>.

The <<FraudPrevention_AVS, Address Verification System (AVS)>> is an
advanced credit card security service that is integrated in the {payment-provider-name}
credit card processing network to help thwart identity theft. When a user makes
an online purchase with a credit card, their billing address is required. The
house number and postal code of the billing address is compared
to the billing address held on file by the card issuing bank. If the address
does not match, the transaction can be declined. AVS is an on-demand service
which is configured by {payment-provider-name}.

See the complete list of the
<<FraudPrevention_AVS_WirecardResponseCodes, {payment-provider-name} Response Codes>>.


include::{root}/include/fields/rest_cc/response/res-avs.adoc[]


[#CC_Fields_xmlelements_response_customfield]
.custom-field

``custom-field`` is a child of
<<CC_Fields_xmlelements_response_payment, payment.custom-fields>>.

{payment-provider-name} can configure ``custom-field`` for you.
For possible field values see the following selected examples. If you need the
values of other card products, please contact our <<ContactUs, Merchant Support>>.

NOTE: As the fields, shown here, have already been defined, _Datatype_ and _Size_ information is not necessary. Please refer to <<CC_Fields_xmlelements_request_customfield, custom-field>> for details.

include::{root}/include/fields/rest_cc/response/res-custom-field.adoc[]


[#CC_Fields_xmlelements_response_cardEMV]
.card.card-emv

include::{root}/include/fields/rest_cc/request/req-card-emv.adoc[tags="**;!request;!requestHeader"]


[#CC_Fields_xmlelements_response_status]
.status

``status`` is a child of <<CC_Fields_xmlelements_response_payment, payment.statuses>>.

``status`` informs merchants about the result of the previously sent
request. They can use this information to redirect consumers to the respective
response page (i.e. success page or failure page).

include::{root}/include/fields/rest_cc/response/res-status.adoc[]


[#CC_Fields_xmlelements_response_threed]
.three-d

``three-d`` is a child of
<<CC_Fields_xmlelements_response_payment, payment>> .

include::{root}/include/fields/rest_cc/response/res-three-d.adoc[]

//-
