[#AppendixK]
== Test Data and Credentials

ifdef::env-wirecard[]

NOTE: Test Credentials are now integrated into the corresponding payment method documentation.
Please follow the link below to find the credentials you are looking
for.

.Credit Card

endif::[]

* *Credit Card:* see
<<CreditCard_TestCredentials, Credit Card Test Credentials>>

[NOTE]
====
Click <<API_CC_TestCards, Test Credit Cards>> to find a list of card numbers to
test 3D Secure and Non-3D Secure cards of different brands.
====

ifdef::env-wirecard[]

.Alternative Payment Methods

* *Alipay Cross-border:* see
<<AlipayCrossBorder_TestCredentials, Alipay Cross-border Test Credentials>>

ifndef::env-nova[]
* *Alipay Domestic:* see
<<AlipayDomestic_TestCredentials, Alipay Domestic Test Credentials>>
* *Bancontact:* see
<<Bancontact_TestCredentials, Bancontact Test Credentials>>
* *Boleto:* see
<<Boleto_TestCredentials, Boleto Test Credentials>>
* *Carrier Billing:* see
<<CarrierBilling_TestCredentials, Carrier Billing Test Credentials>>
* *CIMB Clicks:* see
<<CIMBClicks_TestCredentials, CIMB Clicks Test Credentials>>
endif::[]

* *eps-Überweisung:* see
<<eps_TestCredentials, eps-Überweisung Test Credentials>>

ifndef::env-nova[]
* *giropay:* see
<<giropay_TestCredentials, giropay Test Credentials>>
* *Guaranteed Direct Debit:* see
<<GuaranteedDirectDebit_TestCredentials, Guaranteed Direct Debit Test Credentials>>
* *Guaranteed Invoice by Wirecard:* see
<<GuaranteedInvoice_TestCredentials, Guaranteed Invoice by Wirecard Test Credentials>>
endif::[]

* *iDEAL:* see
<<iDEAL_TestCredentials, iDEAL Test Credentials>>

ifndef::env-nova[]
* *Klarna Guaranteed Invoice and Installments:* see
<<Klarna_TestCredentials, Klarna Test Credentials>>
* *Klarna Payments (Pay now, Pay later, Financing (Slice it)):* see
<<KlarnaV2_TestCredentials, Klarna Pay now, Pay later, Financing (Slice it) Test Credentials>>
* *Masterpass:* see
<<API_Masterpass_TestCredentials, Masterpass Test Credentials>>
* *Maybank2u:* see
<<Maybank2u_TestCredentials, Maybank2u Test Credentials>>
* *MOLPay:* see
<<MOLPay_TestCredentials, MOLPay Test Credentials>>
* *Moneta.ru:* see
<<monetaRu_TestCredentials, moneta.ru Test Credentials>>
//* *paybox:* see<<paybox_TestCredentials, paybox Test Credentials>>
endif::[]

* *Pay by Bank app (Zapp):* see
<<PaybyBankapp_TestCredentials, Pay by Bank app Test Credentials>>

ifndef::env-nova[]
* *Paydirekt:* see
<<paydirekt_TestCredentials, paydirekt Test Credentials>>
* *Payment On Invoice/Payment In Advance:* see
<<POIPIA_TestCredentials, Payment On Invoice/Payment In Advance Test Credentials>>
* *payolution:* see
<<payolution_TestCredentials, payolution Test Credentials>>
endif::[]

* *PayPal:* see
<<PayPal_TestCredentials, PayPal Test Credentials>>

ifndef::env-nova[]
* *Paysafecard:* see
<<paysafecard_TestCredentials, paysafecard Test Credentials>>
* *POLi:* see
<<POLi_TestCredentials, POLi Test Credentials>>
* *Przelewy24 (P24):* see
<<Przelewy24_TestCredentials, P24 Test Credentials>>
endif::[]

* *SEPA:* see
<<SEPADirectDebit_TestCredentials, SEPA Direct Debit Test Credentials>> and
<<SEPACreditTransfer_TestCredentials, SEPA Credit Transfer Test Credentials>>

ifndef::env-nova[]
* *Skrill Digital Wallet:* see
<<SkrillDigitalWallet_TestCredentials, Skrill Digital Wallet Test Credentials>>
endif::[]

* *Sofort.:* see
<<Sofort_TestCredentials, Sofort. Test Credentials>>

ifndef::env-nova[]
* *Trustly:* see
<<Trustly_TestCredentials, Trustly Test Credentials>>
* *TrustPay:* see
<<TrustPay_TestCredentials, TrustPay Test Credentials>>
* *VISA Checkout:* see
<<VISACheckout_TestCredentials, VISA Checkout Test Credentials>>
endif::[]

* *WeChat QRPay:* see
<<WeChatQRPay_TestCredentials, WeChat QRPay Test Credentials>>
* *Wirecard Voucher:* see
<<WirecardVoucher_TestCredentials, Wirecard Voucher Test Credentials>>

//-
endif::[]

//-
