[#Feature_PurchaseReturnAuthorization]
== Update of Refund Transactions for Mastercard and Visa

====
.Advantages
* Faster, easier refund processing.
* No changes in the refund-request (<<CreditCard_TransactionTypes_CaptureAuthorization_SendingData_RefundCapture, refund-capture>>, <<CreditCard_TransactionTypes_Purchase_SendingData_RefundPurchase, refund-purchase>>).
* Enhanced consumer experience: successful refunds show up immediately in your consumers' bank statements.
====

We are updating refund transactions for credit card (Mastercard and Visa). 

With the update, the response to a refund-request returns the ``authorization-code`` as follows:


* If your refund-request is successful, the ``authorization-code`` contains a 6-digit value.
* If the issuer declines the refund-request, the ``authorization-code`` does not contain a value. Please refer to <<StatusCodes_InDetail, ``statuses.status.code``>> for more details.

//-

IMPORTANT: This update comes into effect on *17 April 2020* for all merchants except airlines. +
The ``authorization-code`` does not contain a value prior to that date.

//-