sequenceDiagram

    participant Consumer

    participant Merchant

    participant WPG

    participant Issuer

Consumer->>Merchant: initiates a 3DS2 payment

Merchant->>WPG: sends check-enrollment request

WPG->>WPG: checks card data

WPG->>Merchant: sends check-enrollment response

Merchant->>Issuer: sends PAReq

Issuer->>Consumer: shows authentication UI

Consumer->>Consumer: authenticates card data

Consumer->>Issuer: sends authentication result

Issuer->>Merchant: sends PARes

Merchant->>WPG: sends check-payer-response request

WPG->>Merchant: sends check-payer-response response
