graph LR

A("1. check-enrollment (initial amount)")-->B

B["2. ACS URL redirect"]-->C

C("3. check-payer-response (optional)")-->D

D("4. authorization (initial amount)")-->E

E("5. void-authorization (optional)")

class B squared-rect
