graph LR

A("1. check-enrollment (full amount + interest)")-->B

B["2. ACS URL redirect"]-->C

C("3. check-payer-response (optional)")-->D

D("4. purchase (first installment amount)")

class B squared-rect
