sequenceDiagram

    participant Consumer

    participant Merchant

    participant WPG

    participant eNETS

Consumer->>Merchant: proceeds to checkout

Merchant->>WPG: sends payment request

WPG->>Consumer: asks consumer to select a payment method

Consumer->>WPG: selects eNETS

WPG->>Consumer: redirects consumer to eNETS page

Consumer->>eNETS: selects bank

eNETS->>Consumer: redirects consumer to bank page

Consumer->>eNETS: logs in on bank page and completes payment

eNETS->>WPG: sends transaction status

WPG->>Merchant: sends notification

WPG->>Consumer: redirects to status page
