sequenceDiagram

    participant Consumer

    participant Merchant

    participant {payment-gateway-abbr}

    participant FPX

Consumer->>Merchant: proceeds to checkout

Merchant->>{payment-gateway-abbr}: sends payment request

{payment-gateway-abbr}->>Consumer: asks consumer to select a payment method

Consumer->>{payment-gateway-abbr}: selects FPX

{payment-gateway-abbr}->> Consumer: shows {payment-page-v1-abbr} with available banks for FPX

Consumer->>{payment-gateway-abbr}: selects bank

{payment-gateway-abbr}->>Consumer: redirects consumer to FPX page

FPX->>Consumer: redirects consumer to bank page

Consumer->>FPX: logs in on bank page and completes payment

FPX->>{payment-gateway-abbr}: sends transaction status

{payment-gateway-abbr}->>Merchant: sends notification

{payment-gateway-abbr}->>Consumer: redirects to status page
