sequenceDiagram

    participant Consumer

    participant Merchant

    participant WPG

    participant FPX

Consumer->>Merchant: proceeds to checkout

Merchant->>WPG: sends payment request

WPG->>Consumer: asks consumer to select a payment method

Consumer->>WPG: selects FPX

WPG->> Consumer: shows WPP v1 with available banks for FPX

Consumer->>WPG: selects bank

WPG->>Consumer: redirects consumer to FPX page

FPX->>Consumer: redirects consumer to bank page

Consumer->>FPX: logs in on bank page and completes payment

FPX->>WPG: sends transaction status

WPG->>Merchant: sends notification

WPG->>Consumer: redirects to status page
