sequenceDiagram

    participant M as Merchant

    participant W as WPG

    participant K as Klarna

M-->>M: updates shipping info

M->>W: sends "adjust-capture" request

W->>K: creates and sends "adjust-capture"

K-->>K: updates shipping info

K->>W: sends shipping update response

W->>M: sends "adjust-capture" response

M-->>M: processes response
