sequenceDiagram

    participant M as Merchant

    participant W as WPG

    participant K as Klarna

M-->>M: updates order

M->>W: sends "adjust-authorization" request

W->>K: creates and sends "adjust-authorization"

K-->>K: updates order

K->>W: sends order update response

W-->>W: updates "adjust-authorization"

W->>M: sends response

M-->>M: processes response
