sequenceDiagram

    participant M as Merchant

    participant W as WPG

    participant K as Klarna

M->>W: sends "refund-capture" request

W->>K: creates "refund-capture" transaction

K-->>K: processes refund

K->>W: sends refund result

W->>M: creates/sends response
