sequenceDiagram

    participant A as Consumer

    participant B as Merchants System

    participant C as Hosted Payment Page

    participant D as _{payment-gateway}_

    participant E as Financial Institution

        A ->> B: 1. checks out

        B ->> C: 2. redirects to HPP URL

        D -->> D: 3.a validates signature

	      D ->> C: 3.b returns list of payment methods

        C ->> A: 4. displays payment methods

        C ->> D: 5. posts the payment transaction

        D ->> E: 6. processes payment

        D ->> C: 7. returns final response

        C ->> B: 8. posts response ("success"/"failure")

        opt 1

        B -->> B: 9. validates signature

        B -->> B: decodes response

        end

        A ->> B: redirected to success or failure page
