[#MobilePaymentSDK_IntegrationGuides]
== Mobile Payment SDK

[#MobilePaymentSDK_FirstSteps]
=== First Steps

Before you start coding, you are going to need some credentials:

. Merchant Account ID - the ID of your merchant account that will be
used to process transactions
. Secret Key - a value that you will use to create unique security
signatures for your transactions

//-

[NOTE]
====
You can find testing credentials at this <<API_CC_TestCards, link>>.

Your account needs to be configured through Merchant Support to process mobile
SDK payments.
====

Get your own credentials by contacting <<ContactUs, Merchant Support>>.

Next, depending on where you are from, you will need to choose your
closest production environment: this is where your instance of MPSDK
will be hosted. Both testing and production environments are available
in every location.

At the moment, the supported locations are as follows:

|===
| Location / Name  | Hostname                                     | SSL cert valid until

| Germany - PROD   | ``\https://{instance-hostname}/``               | 03/12/2020
| Germany - TEST   | ``\https://{test-instance-hostname}/``          | 03/12/2020
| Singapore - PROD | ``\https://{instance-hostname}.sg/``            | 05/21/2020
| Singapore - TEST | ``\https://test.{domain}.sg/``           | 09/04/2020
| Toronto - PROD   | ``\https://engine.elastic-payments.com/``    | 08/27/2020
| Toronto - TEST   | ``\https://sandbox-engine.thesolution.com/`` | 12/01/2019
|===

WARNING: Don't forget to keep _MPSDK_ up-to-date (i.e. updating before the SSL
certification expires).