[#ShopSystems]
== Shop Extensions

video::jO_86Hj0I60[youtube, width=640, height=360]

We offer you various shop extensions which you are able to
use *free-of-charge* to add payment functionality to your online shop
system. Therefore you only need to download/install our shop extension to
your online shop and to configure it to your needs.

Some shop systems refer to these shop extensions as "app", as
"add-on" or as "module". However, for the purpose of better legibility,
we call all of them "shop extensions" within this documentation.

All our shop extensions require *only PCI SAQ A* certification for credit
card payments which you may achieve very easily.

You are able to *test the shop extension* features and functionality via
pre-configured test accounts for each payment method. For going live you
need your personal credentials which you receive from Wirecard after
concluding a corresponding contract. Please contact our <<ContactUs, sales and support teams>>.

All our shop extensions are developed and offered as *open source* on link:https://github.com/wirecard[GitHub]. This means you are able
to use them free-of-charge, have full access to the source code and are
able to do forks, raise issues or do contributions.

Please have a look on
our <<ShopSystems_TermsOfUse, Terms of Use and Legal Notice>> before you use our shop extensions in your online
shop.

.Currently we offer shop extensions for the following shop systems:
[cols="18,50a,22a,10a"]
|===
|Shop System   |Supported Payment Methods |Supported Languages |Documentation
a| Magento 1

- https://github.com/wirecard/magento-ee/releases[GitHub] |
      - Credit Card
      - Alipay Cross-border
      - eps-Überweisung
      - giropay
      - Guaranteed Invoice by payolution
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Pay by Bank app
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort. |
//a| Magento 1

//- https://github.com/wirecard/magento-ee/releases[GitHub] |
//      - Credit Card
//      - eps-Überweisung
//      - iDEAL
//      - PayPal
//      - SEPA Credit Transfer
//      - SEPA Direct Debit |

      - English
      - German  |

      - https://github.com/wirecard/magento-ee/wiki[English]

a| Magento 2

- https://github.com/wirecard/magento2-ee/releases[GitHub] |
      - Credit Card
      - Alipay Cross-border
      - giropay
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Pay by Bank app
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort. |
//a| Magento 2

//- https://github.com/wirecard/magento2-ee/releases[GitHub]|
//      - Credit Card
//      - iDEAL
//      - PayPal
//      - SEPA Credit Transfer
//      - SEPA Direct Debit |

      - Chinese, simplified
      - Chinese, traditional
      - English
      - French
      - German
      - Indonesian
      - Japanese
      - Korean  |

      - https://github.com/wirecard/magento2-ee/wiki[English]
      - https://github.com/wirecard/magento2-ee/wiki/Accueil[French]

a| OpenCart

- https://github.com/wirecard/opencart-ee/releases[GitHub]
- https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=34860[Marketplace] |
      - Credit Card
      - Alipay Cross-border
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Maestro SecureCode
      - Masterpass
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International |
//a| OpenCart

//- https://github.com/wirecard/opencart-ee/releases[GitHub]
//- https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=34860[Marketplace] |
//      - Credit Card
//      - iDEAL
//      - PayPal
//      - SEPA Credit Transfer
//      - SEPA Direct Debit |

      - Chinese, simplified
      - Chinese, traditional
      - English
      - German
      - Indonesian
      - Japanese
      - Korean   |

      - https://github.com/wirecard/opencart-ee/wiki[English]

a| OXID

- https://github.com/wirecard/oxid-ee/releases[GitHub]
- https://exchange.oxid-esales.com/de/en/By-Distributor/Wirecard-AG/[Marketplace]
 |
      - Credit Card
      - eps-Überweisung
      - giropay
      - Guaranteed Invoice by payolution
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort. |
//a| OXID

//- https://github.com/wirecard/oxid-ee/releases[GitHub]
//- https://exchange.oxid-esales.com/de/en/By-Distributor/Wirecard-AG/[Marketplace] |
//      - Credit Card
//      - eps-Überweisung
//      - iDEAL
//      - PayPal
//      - SEPA Credit Transfer
//      - SEPA Direct Debit |

      - English
      - German  |

      - https://github.com/wirecard/oxid-ee/wiki[English]

a| PrestaShop

- https://github.com/wirecard/prestashop-ee/releases[GitHub] |
      - Credit Card
      - Alipay Cross-border
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - Przelewy24
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort. |

//| PrestaShop

//- https://github.com/wirecard/prestashop-ee/releases[GitHub] |
//      - Credit Card
//      - iDEAL
//      - PayPal
//      - SEPA Credit Transfer
//      - SEPA Direct Debit |

      - Chinese, simplified
      - Chinese, traditional
      - English
      - French
      - German
      - Indonesian
      - Japanese
      - Korean
      - Polish  |

      - https://github.com/wirecard/prestashop-ee/wiki[English]
      - https://github.com/wirecard/prestashop-ee/wiki/Accueil[French]

a| Salesforce Commerce Cloud

- https://github.com/wirecard/salesforce-ee/releases[GitHub]
- https://www.salesforce.com/products/commerce-cloud/partner-marketplace/partners/wire-card/[Marketplace] |
      - Credit Card
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort. |
//a| Salesforce Commerce Cloud

//- https://github.com/wirecard/salesforce-ee/releases[GitHub]
//- https://www.salesforce.com/products/commerce-cloud/partner-marketplace/partners/wire-card/[Marketplace] |
//      - Credit Card
//      - PayPal
//      - SEPA Credit Transfer
//      - SEPA Direct Debit |

      - English |

      - https://github.com/wirecard/salesforce-ee/wiki[English]


a| SAP Commerce

- https://github.com/wirecard/sap-commerce-ee/releases[GitHub]
- https://www.sapappcenter.com/apps/28091#!overview[Marketplace] |
      - Credit Card
      - Alipay Cross-border
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Masterpass
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Direct Debit
      - Sofort. |
//a| SAP Commerce

//- https://github.com/wirecard/sap-commerce-ee/releases[GitHub]
//- https://www.sapappcenter.com/apps/28091#!overview[Marketplace] |
//      - Credit Card
//      - iDEAL
//      - PayPal
//      - SEPA Direct Debit |

      - English
      - German   |

      - https://github.com/wirecard/sap-commerce-ee/wiki[English]


a| Shopify

- https://github.com/wirecard/shopify-ee[GitHub] |
      - Credit Card
      - Pay by Bank app
      - PayPal
      - SEPA Direct Debit
      - Sofort.               |

//a|  Shopify

//- https://github.com/wirecard/shopify-ee[GitHub] |
//      - Credit Card
//      - PayPal
//      - SEPA Direct Debit |

      - Chinese, simplified
      - Chinese, traditional
      - English
      - French
      - German
      - Indonesian
      - Japanese
      - Korean    |

      - https://github.com/wirecard/shopify-ee/wiki[English]
      - https://github.com/wirecard/shopify-ee/wiki/Accueil[French]

a| Shopware

- https://github.com/wirecard/shopware-ee/releases[GitHub]
- https://store.shopware.com/en/wirec97652863074f/wirecard-payment-gateway-shop-extension.html[Marketplace]|
      - Credit Card
      - Alipay Cross-border
      - eps-Überweisung
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Masterpass
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International |
//a| Shopware

//- https://github.com/wirecard/shopware-ee/releases[GitHub]
//- https://store.shopware.com/en/wirec97652863074f/wirecard-payment-gateway-shop-extension.html[Marketplace] |
//      - Credit Card
//      - eps-Überweisung
//      - iDEAL
//      - PayPal
//      - SEPA Credit Transfer
//      - SEPA Direct Debit |

      - English
      - German   |

      - https://github.com/wirecard/shopware-ee/wiki[English]

a| WooCommerce

- https://github.com/wirecard/woocommerce-ee/releases[GitHub]
- https://wordpress.org/plugins/wirecard-woocommerce-extension/[Marketplace] |
      - Credit Card
      - Alipay Cross-border
      - eps-Überweisung
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Masterpass
      - Pay by Bank app
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort. |
//| WooCommerce

//- https://github.com/wirecard/woocommerce-ee/releases[GitHub]
//- https://wordpress.org/plugins/wirecard-woocommerce-extension/[Marketplace] |
//      - Credit Card
//      - eps-Überweisung
//      - iDEAL
//      - PayPal
//      - SEPA Credit Transfer
//      - SEPA Direct Debit |

      - Chinese, simplified
      - Chinese, traditional
      - English
      - French
      - German
      - Indonesian
      - Japanese
      - Korean   |

      - https://github.com/wirecard/woocommerce-ee/wiki[English]
      - https://github.com/wirecard/woocommerce-ee/wiki/Accueil[French]
      - https://github.com/wirecard/woocommerce-ee/wiki/Startseite[German]

|===

If you require another shop system not listed here or if you need
additional payment methods or languages,
please <<ContactUs, contact our sales and support teams>>.

.Adding payment methods

Add more payments methods with the
link:https://github.com/wirecard/paymentSDK-php[Wirecard PHP Payment SDK] or
our <<PaymentMethods, {payment-gateway} payment methods>>.

Want to contribute? Send us a pull-request on GitHub and we will get in
touch with you.


.Our shop extensions offer the following functionalities:

- *Credit card* payments based on a *seamless integration* via Seamless
Payment Page, so that your consumers have a perfectly integrated payment
experience in your online shop.
- All our shop extensions require *only PCI DSS SAQ A*, which is the
easiest possible PCI SAQ level, so that you do not need to hassle with
PCI related details.
- All *alternative payment methods* are integrated via REST API of our
{payment-gateway} to offer all features and
flexibility in integration for each payment method.
- All payment methods are integrated individually which enables you
to *configure* them separately to your specific demand.
- Post-processing operations (like *capture, refund or cancel*) for each
payment method are directly supported in the back-end of the shop
system, so that your transactions within Wirecard are synchronized to
the orders in your online shop.
- Support of *one-click-checkout for credit card* payments, so that
recurring consumers of your online shop can easily and fast do their
further payments.
- Integration of a *live-chat with our support team* within the
configuration of the shop extension and offered features and payment
methods, so that you get a quick and interactive help when and where you
need it.
- Integration to *Wirecard Risk Management*, so that you are able to use
risk and fraud tools to reduce fraudulent transactions in your online
shop.
- Regular *updates of all of our shop extensions* to offer you
compatibility to the current versions of shop systems.

//-

.Advantages of using shop extensions developed and maintained by Wirecard

- All our shop extensions are based on the principles of *open source* development and available for free for everyone.
- You are able to download, install and configure the shop extension and do
as many *test transactions* as you want to do.
- All shop extensions are available with their complete *source code* and *history*
of all changes, so that you are able to change the
shop extension to your business need.
- We offer you *free support by email or phone* if you have any
questions regarding the installation and configuration of our shop extensions.
- You and your integrator are able to *raise issues, make pull requests or create forks* within all functionality GitHub offers to you.
- You are able to *contribute* to improve a shop extension, so that your
features are also available within all new versions we are releasing.

//-

Finally, feel free to take a look at <<ShopSystems_Myths, Myths regarding the usage of a shop extension in your online shop>>.

[#ShopSystems_TermsOfUse]
=== Terms of Use

. The extensions offered are provided free of charge by Wirecard AG and
are explicitly not part of the Wirecard AG range of products and
services.
. They have been tested and approved for full functionality in the
standard configuration (status on delivery) of the corresponding shop
system. They are under General Public License Version 3 (GPLv3) and can
be used, developed and passed on to third parties under the same terms.
. However, Wirecard AG does not provide any guarantee or accept any
liability for any errors occurring when used in an enhanced, customized
shop system configuration.
. Operation in an enhanced, customized configuration is at your own
risk and requires a comprehensive test phase by the user of the extension.
. Customers use the extensions at their own risk. Wirecard AG does not
guarantee their full functionality neither does Wirecard AG assume
liability for any disadvantages related to the use of the extensions.
Additionally, Wirecard AG does not guarantee the full functionality for
customized shop systems or installed extensions of other vendors of extensions
within the same shop system.
. Customers are responsible for testing the extension's functionality
before starting productive operation.
. By installing the extension into the shop system the customer agrees to
these terms of use. Please do not use the extension if you do not agree to
these terms of use!
. Uninstalling the extension may result in the loss of data.

//-

[#ShopSystems_LegalNotes]
==== Legal Notes

No warranty whatsoever can be granted on any alterations and/or new
implementations as well as resulting diverging usage not supported or
described within this documentation.

[#ShopSystems_Myths]
=== Common Misconceptions

====
"My payment processes have to fit perfectly to that processes offered by the
shop system, otherwise I have to adapt either the shop extension or my processes!"
====

We are integrating the {payment-gateway} based on the
standards of the corresponding shop system. This enables us a very tight
integration of our interface to the default payment process offered by
the shop system. Therefore our payment processes are integrated as
intended by the shop system. +
If you, as a merchant, require different processes than offered by the
shop system and our shop extension, you have the following possibilities:

. Re-think your decision choosing your shop system. Maybe another shop
system fits better to your processes.
. Adapt the shop system and maybe also the shop extension to your
business needs. This is possible for nearly all shop systems, because
they offer an open source version you are allowed to modify as you want.

//-

---

====
"I will have additional costs due to changes in the
source code of the shop extension which have to be done by my developers or
my integrator and they are not used to the structure and source code
of the shop extension!"
====

or
====
"If my processes will be required to change, then I have to adopt
the shop extension again. An integration by my own would be more flexible
for me!"
====

or
====
In the long run, the sum of efforts to update and maintain the
shop extension is much higher than a personalized integration. Additionally,
I have to consider that it takes much time to update a shop extension!
====

or
====
"I have heard from other merchants that a direct and personal
integration to my online shop is much faster and cheaper than using a
shop extension!"
====

Overall seen it is always much cheaper and faster for you as merchant to
start with a full-featured and functional shop extension tailored and
deeply integrated into your shop system. Otherwise, if you do the
integration on your own from scratch you have to deal with all the
payment related details of the shop system and the integration details
of the payment interfaces to Wirecard. +
Additionally, a shop extension offers the following advantages:

. We are constantly maintaining and updating our shop extensions
regarding the updates of the shop system, integration of payment methods
and adding new features. If you do the integration on your own from
scratch you have to do this solely on your own which may end in permanent
attention and effort to keep track with the shop system, regulations and
security updates.
. If your changes and adoptions are of interest also for other
integrators or developers, you may raise a pull-request on GitHub and
our developers will check your contribution. If it is fine, we will add
it to the source code of our shop extension, so that for each new version
of our shop extension your changes/adoptions are part of a release and you
do not need to adopt it every time we do an update.

//-

Even if you decide to do your own integration from scratch, please
keep in mind to use our shop extension as a "blue print" which may help you
regarding the implementation of various features, workflows and payment
methods.

---

====
"If there is a new version of the shop extension, I have to redo all
my manual changes again!"
====

Within the update of a shop extension your configuration and your already
existing transactions are also available in the new version of the shop
extension. If you did only small changes in your shop extension installation,
you may find the differences easy via your version control system and
are able to merge them to the updated shop extension. If there are larger
changes regarding functionality you may consider to raise a pull-request
in GitHub, so that our developers may integrate your feature to the shop
system and then this feature will also be part of each new version we
release.

---

====
"Shop extensions are not as often and as fast updated as I require it!"
====

If there are no substantial changes in the interface of the shop system
and the payment process, our shop extension will work out-of-the-box also
with newer versions of the shop system, especially if there are only
minor updates of the shop system itself. +
We at Wirecard are doing our best to have our shop extensions as near as
possible to the releases of the shop vendors. But we are not able to
guarantee that we can do an update on a daily-basis and in comparison to
the market we do updates very fast and have had a proven
track for many years. +
On the other hand if you do the integration on your own, you have to
check and update your own integration also.

---

====
"Shop extensions cause troubles in conjunction with other extensions I
have installed within my shop system!"
====

All our shop extensions are developed strictly to the rules, frameworks and
hooks of the shop system. Therefore, you are able to use our shop extensions
in parallel within one shop and we do not interfere with other shop extensions
you may have installed in your shop system. If there are troubles with
other shop extensions disturbing the payment process, we would like to
recommend you to disable these extensions or check for a newer and
compatible version. If this does not solve the problem, please contact
our support teams, so we can maybe find a workaround for you.

---

====
"Shop extensions only support the current version of the shop system
and therefore you have to update your shop system to use the shop
extension!"
====

If you want to use an older version of our shop extension, you can find and
download all previously released versions directly from GitHub. Even we
offer this, we strongly recommend that you update your shop system
accordingly to the releases of the shop vendor, so that your online shop
is up-to-date regarding features, functions and security. +
If you may have other or additional doubts, please do not hesitate to
contact our <<ContactUs, sales and support teams>>.

//-